version: '3.8'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build: 
      context: $BACKEND_ROOT
      dockerfile: ./Dockerfile
    ports:
      - ${BACKEND_PORT}:4000/tcp
    volumes:
      - ./backend:/backend
    environment:
      - TSC_WATCHFILE=UseFsEvents
      - NODE_ENV=development
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - BACKEND_PORT=${BACKEND_PORT}
    restart: always
  
  frontend:
      build: 
        context: $FRONTEND_ROOT
        dockerfile: ./Dockerfile
        target: prepare
      ports:
        - ${FRONTEND_PORT}:3000/tcp
      volumes:
        - ./frontend:/frontend
      restart: always

volumes:
  postgres-data: