#!/bin/bash
export POSTGRES_HOST=postgres
export POSTGRES_PORT=5432
export POSTGRES_USER=grocery
export POSTGRES_PASSWORD=123qwe
export POSTGRES_DB=grocery

export BACKEND_ROOT=./backend
export BACKEND_PORT=4000

export FRONTEND_ROOT=./frontend
export FRONTEND_PORT=3000