import { Inter } from 'next/font/google';

import { Header } from '@/components';

import style from './layout.module.scss';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={style.root}>
          <Header />
          {children}
        </div>
      </body>
    </html>
  )
}
